create table application_import (
    id int8 not null,
    createTime timestamp,
    createUser varchar(255),
    deleted boolean,
    updateTime timestamp,
    updateUser varchar(255),
    businessService varchar(255),
    description varchar(255),
    applicationname varchar(255),
    comments varchar(255),
    recordType1 varchar(255),
    tag1 varchar(255),
    tagType1 varchar(255),
    tag2 varchar(255),
    tagType2 varchar(255),
    tag3 varchar(255),
    tagType3 varchar(255),
    tag4 varchar(255),
    tagType4 varchar(255),
    errorMessage varchar(255),
    isValid boolean,
    primary key (id)
)